# Generated by Django 3.1.3 on 2021-10-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naner', '0008_auto_20211013_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='author',
        ),
    ]
