# Generated by Django 3.1.3 on 2021-10-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naner', '0013_auto_20211013_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
